# This is a basic workflow to help you get started with Actions

name: Test, Build and Release APK

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Flutter environment setup action
    - name: Flutter Environment Setup
      uses: subosito/flutter-action@v1.2.0

    # Get necessary packages
    - name: Get Packages
      run: flutter pub get  
      
    # Runs the defined test cases
    - name: Run tests
      run: flutter test
      
    - run: flutter build apk --debug --split-per-abi
    - name: Push APK to Release Folder
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/debug/*.apk"
        token: ${{ secrets.ACTIONS_API_TOKEN }}
